pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git 'https://github.com/Shashankgowdasp/User-Login-CICD.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build Docker image
                sh 'docker build -t userlogin:1.0 .'
            }
        }

        stage('Run Docker Container') {
            steps {
                // Run Docker container
                sh 'docker run -d --name userlogin-container-v3 -p 8083:8080 userlogin:1.0'
            }
        }
    }

    post {
        success {
            echo 'Docker container is running successfully!'
        }
        failure {
            echo 'Build or Deployment failed!'
        }
    }
}
