pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Shashankgowdasp/User-Login-CICD.git'
            }
        }
        stage('Build') {
            steps {
                // Add your build commands here
                echo 'Building the project...'
            }
        }
        stage('Test') {
            steps {
                // Add test commands here
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                // Add deployment commands here
                echo 'Deploying the application...'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
